
name: Publish NPM Package
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/9-jobber-shared
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build
      - run: |
          echo @<your-github-username>:https://npm.pkg.github.com/ > build/.npmrc
          echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> build/.npmrc
      - run: npm publish
        working-directory: ./build
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}